/*
 * API Title
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	api "github.com/gergelyszaz/home-service/gen"
	service "github.com/gergelyszaz/home-service/service"
)

func main() {
	log.Printf("Server started")

	DefaultApiService := service.NewApiService()
	DefaultApiController := api.NewDefaultApiController(DefaultApiService)

	router := service.NewRouter(DefaultApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
