openapi: 3.0.2
info:
  title: API Title
  version: "1.0"
servers:
- url: https://api.server.test/v1
security:
- BasicAuth: []
paths:
  /health:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/service_status'
                type: array
          description: OK
      security:
      - basicAuth: []
  /health/{service}:
    post:
      parameters:
      - explode: false
        in: path
        name: service
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: OK
      security:
      - basicAuth: []
  /wake:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wake_status'
          description: OK
      security:
      - basicAuth: []
    post:
      responses:
        "202":
          description: Accepted
      security:
      - basicAuth: []
components:
  schemas:
    wake_status:
      example:
        wake_device: true
      properties:
        wake_device:
          type: boolean
      required:
      - wake_device
      type: object
    service_status:
      example:
        service: service
        updatedAt: ""
      properties:
        service:
          type: string
        updatedAt:
          type: date
      required:
      - service
      - updatedAt
      type: object
  securitySchemes:
    BasicAuth:
      scheme: basic
      type: http
